version: '3.9'

services:
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${DB_NAME:-todos_database}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD:-password}
    depends_on:
      - mongodb

  ms_broker:
      build: .
      ports:
        - 3000:3000
      environment:
        - PORT=4000
        - DB_USERNAME=${DB_USERNAME:-root}
        - DB_PASSWORD=${DB_PASSWORD:-password}
        - DB_NAME=${DB_NAME:-todos_database}
        - DB_HOST=mongodb://mongodb:27017
      depends_on:
        - mongodb

  books:
    build: .
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-todos_database}
      - DB_HOST=mongodb://mongodb:27017
    depends_on:
      - mongodb

  counter:
    build: .
    ports:
      - 4010:4010
    environment:
      - PORT=4000
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-todos_database}
      - DB_HOST=mongodb://mongodb:27017
    depends_on:
      - mongodb
